/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.emi;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.UnsupportedEncodingException;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.Timer;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ararage
 */
public class CrearDocumento extends javax.swing.JFrame {

    /**
     * Creates new form CrearDocumento
     */
    public CrearDocumento() {
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.labelError.setVisible(false);
        this.labelError.setText("");
        this.labelErrorFCA.setVisible(false);
        this.labelErrorFCA.setText("");
        this.labelErrorFechaDoc.setVisible(false);
        this.labelErrorFechaDoc.setText("");
        this.labelErrorFechaFCA.setVisible(false);
        this.labelErrorFechaFCA.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        labelError = new javax.swing.JLabel();
        labelErrorFCA = new javax.swing.JLabel();
        labelErrorFechaFCA = new javax.swing.JLabel();
        labelErrorFechaDoc = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sistema de Control y Seguimiento de Coordenadas");

        jLabel2.setText("Ingrese No. F.C.A.");

        jLabel3.setText("Fecha F.C.A.");

        jLabel4.setText("Fecha de documento");

        try{
            jFormattedTextField1 =
            new JFormattedTextField(new MaskFormatter("########"));
        }catch(java.text.ParseException e){
            e.printStackTrace();
        }
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        try{
            jFormattedTextField2 =
            new JFormattedTextField(new MaskFormatter("##/##/####"));
        }catch(java.text.ParseException e){
            e.printStackTrace();
        }
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });

        try{
            jFormattedTextField3 =
            new JFormattedTextField(new MaskFormatter("##/##/####"));
        }catch(java.text.ParseException e){
            e.printStackTrace();
        }
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelError.setText("jLabel5");

        labelErrorFCA.setText("jLabel6");

        labelErrorFechaFCA.setText("jLabel7");

        labelErrorFechaDoc.setText("jLabel8");

        jMenu3.setText("Archivo");

        jMenuItem1.setText("Menu Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Cerrar Sesión");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelErrorFCA)
                    .addComponent(labelErrorFechaFCA)
                    .addComponent(labelErrorFechaDoc))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelErrorFCA))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelErrorFechaFCA)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelErrorFechaDoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(labelError)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if((jFormattedTextField1 != null && !jFormattedTextField1.getText().equals("")) && 
            (jFormattedTextField2 != null && !jFormattedTextField2.getText().equals("")) &&
            (jFormattedTextField3 != null && !jFormattedTextField3.getText().equals(""))){
            boolean fechaFCA = false;
            boolean fechaDoc = false;
            boolean fca_ = false;
            //Verificamos si la fecha FCA es valida
            SimpleDateFormat dateF = new SimpleDateFormat("dd/mm/yyyy");
            try{
                dateF.parse(jFormattedTextField2.getText());
                fechaFCA = true;
            }catch(ParseException e){
                this.labelErrorFechaFCA.setVisible(true);
                this.labelErrorFechaFCA.setText("Fecha FCA invalida");
            }
            try{
                dateF.parse(jFormattedTextField3.getText());
                fechaDoc = true;
            }catch(ParseException e){
                this.labelErrorFechaDoc.setVisible(true);
                this.labelErrorFechaDoc.setText("Fecha Doc invalida");
            }
            //jFormattedTextField1.setText(jFormattedTextField1.getText() < 8 );
            //boolean fcaValido = (jFormattedTextField1.getText().length() < 8) ? this.labelErrorFCA.setVisible(true):this.labelErrorFCA.setVisible(false);
            if (jFormattedTextField1.getText().length() < 8){
                this.labelErrorFCA.setVisible(true);
                this.labelErrorFCA.setText("Error en el FCA");
            }else{
                fca_ = true;
            }
            
            if(fca_ && fechaFCA && fechaFCA){
                String fca = jFormattedTextField1.getText()+"|"+
                        jFormattedTextField2.getText()+"|"+ 
                        jFormattedTextField3.getText()+"\n";
                this.labelError.setVisible(true);
                this.labelErrorFCA.setVisible(false);
                this.labelErrorFechaDoc.setVisible(false);
                this.labelErrorFechaFCA.setVisible(false);
                this.labelError.setText("Guardado Exitosamente");
                this.guardarFCA(fca);
                redirect();
            }
        }else{
            this.labelError.setVisible(true);
            this.labelError.setText("Llena todos los campos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void redirect(){
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Reading SMTP Info.");
                new Menu().setVisible(true);
                hideThis();
            }
        };
        Timer timer = new Timer(3000 ,taskPerformer);
        timer.setRepeats(false);
        timer.start();
    }
    
    private void hideThis(){
        this.setVisible(false);
    }
    
    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    private void guardarFCA(String fca){
        if(!new File("temp.dat").isFile()){
            try (Writer writer = new BufferedWriter(new OutputStreamWriter(
                 new FileOutputStream("temp.dat"), "utf-8"))) {
                writer.write(fca);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(CrearDocumento.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(CrearDocumento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            String content;
            try {
                content = new String(Files.readAllBytes(Paths.get("temp.dat")));
                System.out.println(content);
                Files.write(Paths.get("temp.dat"), fca.getBytes(), StandardOpenOption.APPEND);
            } catch (IOException ex) {
                Logger.getLogger(CrearDocumento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelErrorFCA;
    private javax.swing.JLabel labelErrorFechaDoc;
    private javax.swing.JLabel labelErrorFechaFCA;
    // End of variables declaration//GEN-END:variables
}
